services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity

    user: "1000"
    privileged: true
    environment:
      SHELL: /bin/zsh

    volumes:
      - command.history:/commandhistory
      - go.cache.mod:/home/hypnos/go/pkg/mod
      - go.cache.bin:/home/hypnos/.cache/go-build

      - ..:/workspace
      - ${HOME}/workspaces:/workspaces
      - ${HOME}/.claude:/home/hypnos/.claude

  registry:
    image: ghcr.io/project-zot/zot:v2.1.12
    command: ["serve", "/_/config.json"]
    user: "1000:1000"

    volumes:
      - type: bind
        source: ./zot
        target: /_

volumes:
  command.history:
  go.cache.mod:
  go.cache.bin:
